title = "Config"

[web]
  addr = ":8080"
  tmpl = "templates"

[api]

  [api.grpc]
  addr = "0.0.0.0:8000"
  timeout = "1s"

  [api.http]
  addr = "0.0.0.0:9000"
  timeout = "1s"

[ms]

  [bbc]
  title = "bbc"
  domain = "www.bbc.com"
  url = "http://www.bbc.com"
  port = 10001
  timeout = "1s"

